
---

# =============================================================================
# Dependabot Configuration
# =============================================================================

version: 2

updates:

  # Git Submodule dependencies
  # ===========================================================================

  -
    package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-gitsubmodule"
      include: "scope"
    labels:
      - "dependencies"
      - "gitsubmodule"


  # GitHub Actions dependencies
  # ===========================================================================

  -
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"


  # Docker dependencies
  # ===========================================================================

  -
    package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"


  # devContainer dependencies
  # ===========================================================================

  -
    package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-devcontainer"
      include: "scope"
    labels:
      - "dependencies"
      - "devcontainer"

  -
    package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-devcontainer"
      include: "scope"
    labels:
      - "dependencies"
      - "devcontainer"


  # PIP dependencies
  # ===========================================================================

  -
    package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-pip"
      include: "scope"
    labels:
      - "dependencies"
      - "pip"


  # NPM dependencies
  # ===========================================================================

  -
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"


  # Rust dependencies
  # ===========================================================================

  -
    package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-cargo"
      include: "scope"
    labels:
      - "dependencies"
      - "cargo"


  # PHP dependencies
  # ===========================================================================

  -
    package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-composer"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"


  # Go dependencies
  # ===========================================================================

  -
    package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-gomod"
      include: "scope"
    labels:
      - "dependencies"
      - "gomod"


  # Terraform dependencies
  # ===========================================================================

  -
    package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"


  # .NET dependencies
  # ===========================================================================

  -
    package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-nuget"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"

  -
    package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-dotnet-sdk"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet-sdk"


  # Erlang dependencies
  # ===========================================================================

  -
    package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-mix"
      include: "scope"
    labels:
      - "dependencies"
      - "mix"


  # Java dependencies
  # ===========================================================================

  -
    package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-maven"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
