import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        ignores: [
            "dist/**",
            "coverage/**",
            "node_modules/**",
            // Generated by scripts/build-icons.mjs
            "src/ts/icons/**",
            "src/ts/icons.ts",
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        languageOptions: {
            globals: { ...globals.browser },
        },
    },
    {
        files: ["scripts/**/*.mjs", "*.config.{js,ts}"],
        languageOptions: {
            globals: { ...globals.node },
        },
    },
    {
        files: ["**/*.test.ts"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
        },
    }
);
