FROM ubuntu:22.04

# non interactive frontend for locales
ENV DEBIAN_FRONTEND=noninteractive


# # Use the official Node.js 14 image as a parent image
# FROM node:14

# # Set the working directory in the container
# WORKDIR /usr/src/app

# # Copy the package.json and package-lock.json (if available) to the container
# COPY package*.json ./

# # Install any dependencies
# RUN npm install

# # Copy the project files to the container
# COPY . .

# # Build the TypeScript project (if necessary)
# RUN npm run build

# # Specify the command to run the app
# CMD ["node", "dist/index.js"]
