// ============================================================================
// icon.gl | Font Build Script
// ============================================================================
// Generates the icon font from src/svg/**/*.svg using Fantasticon and
// regenerates src/scss/variables/_font.scss so the SCSS $icongl_map stays in
// sync with the actual font codepoints. Icon ids are derived from the SVG
// basename only (folder names are NOT prefixed) so the SCSS classes match
// the SVG file names: e.g. src/svg/app/app_solution.svg -> .i_app_solution.
// ============================================================================

import { FontAssetType, generateFonts, OtherAssetType } from "fantasticon";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");

const INPUT_DIR = path.join(ROOT, "src/svg");
const OUTPUT_DIR = path.join(ROOT, "dist/font");
const FONT_NAME = "icongl";
const SCSS_OUT = path.join(ROOT, "src/scss/variables/_font.scss");

// Skip lucide icons — they are stroke-based, not fill-based, and don't render
// correctly when converted to a glyph font.
const SKIP_FOLDERS = new Set(["lucide"]);

async function collectSvgs(dir) {
    const seen = new Map();
    async function walk(d) {
        const entries = await fs.readdir(d, { withFileTypes: true });
        for (const e of entries) {
            const p = path.join(d, e.name);
            if (e.isDirectory()) {
                if (SKIP_FOLDERS.has(e.name)) continue; // skip excluded folders
                await walk(p);
            } else if (e.isFile() && e.name.endsWith(".svg")) {
                const id = path.basename(e.name, ".svg");
                if (seen.has(id)) {
                    throw new Error(
                        `Duplicate icon id "${id}":\n  ${seen.get(id)}\n  ${p}`
                    );
                }
                seen.set(id, p);
            }
        }
    }
    await walk(dir);
    return seen;
}

function renderScss(codepoints) {
    const names = Object.keys(codepoints).sort();
    const lines = [];
    lines.push("// AUTO-GENERATED by scripts/build-font.mjs — do not edit by hand.");
    lines.push("// Source of truth: src/svg/**/*.svg + dist/font/icongl.json.");
    lines.push("");
    lines.push("// ============================================================================");
    lines.push("// Icon.gl | Font Variables");
    lines.push("// ============================================================================");
    lines.push("");
    lines.push(`$icon_name: "${FONT_NAME}" !default;`);
    lines.push(`$icon_dir: "../font" !default;`);
    lines.push("");
    lines.push("$icongl_font_formats: (");
    lines.push('    "woff2": "woff2",');
    lines.push('    "woff": "woff",');
    lines.push(");");
    lines.push("");
    lines.push("$icongl_map: (");
    for (const name of names) {
        const hex = codepoints[name].toString(16);
        lines.push(`    "${name}": "\\${hex}",`);
    }
    lines.push(");");
    lines.push("");
    return lines.join("\n");
}

async function main() {
    await fs.mkdir(OUTPUT_DIR, { recursive: true });

    const svgs = await collectSvgs(INPUT_DIR);
    console.log(
        `[build-font] ${svgs.size} svg sources discovered (no name collisions)`
    );

    // Copy SVGs to a temp folder (Fantasticon doesn't support filtering)
    const TEMP_DIR = path.join(ROOT, ".font-build-tmp");
    await fs.rm(TEMP_DIR, { recursive: true, force: true });
    await fs.mkdir(TEMP_DIR, { recursive: true });

    for (const [id, srcPath] of svgs.entries()) {
        const destPath = path.join(TEMP_DIR, `${id}.svg`);
        await fs.copyFile(srcPath, destPath);
    }
    console.log(`[build-font] copied ${svgs.size} SVGs to temp folder`);

    await generateFonts({
        inputDir: TEMP_DIR,
        outputDir: OUTPUT_DIR,
        name: FONT_NAME,
        fontTypes: [FontAssetType.WOFF2, FontAssetType.WOFF],
        assetTypes: [OtherAssetType.JSON, OtherAssetType.TS],
        normalize: true,
        getIconId: ({ basename }) => basename,
    });

    // Clean up temp folder
    await fs.rm(TEMP_DIR, { recursive: true, force: true });

    const jsonPath = path.join(OUTPUT_DIR, `${FONT_NAME}.json`);
    const codepoints = JSON.parse(await fs.readFile(jsonPath, "utf8"));
    const fontIds = new Set(Object.keys(codepoints));

    const missing = [...svgs.keys()].filter((id) => !fontIds.has(id));
    if (missing.length) {
        throw new Error(
            `[build-font] ${missing.length} svgs missing from font: ` +
                missing.slice(0, 10).join(", ") +
                (missing.length > 10 ? ", ..." : "")
        );
    }
    console.log(`[build-font] ${fontIds.size} icons in font, all svgs covered`);

    await fs.writeFile(SCSS_OUT, renderScss(codepoints), "utf8");
    console.log(`[build-font] wrote ${path.relative(ROOT, SCSS_OUT)}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
