// ============================================================================
// icon.gl | Font Build Script
// ============================================================================
// Generates the icon font from src/svg/**/*.svg using Fantasticon and
// regenerates src/scss/variables/_font.scss so the SCSS $icongl_map stays in
// sync with the actual font codepoints. Icon ids are derived from the SVG
// basename only (folder names are NOT prefixed) so the SCSS classes match
// the SVG file names: e.g. src/svg/app/app_solution.svg -> .i_app_solution.
// ============================================================================

import { FontAssetType, generateFonts, OtherAssetType } from "fantasticon";
import fs from "node:fs/promises";
import path from "node:path";
import { collectIcons, ROOT } from "./icon-sources.mjs";

const OUTPUT_DIR = path.join(ROOT, "dist/font");
const TEMP_DIR = path.join(ROOT, ".font-build-tmp");
const FONT_NAME = "icongl";
const SCSS_OUT = path.join(ROOT, "src/scss/variables/_font.scss");

// Skip lucide icons — they are stroke-based, not fill-based, and don't render
// correctly when converted to a glyph font.
const SKIP_FOLDERS = new Set(["lucide"]);

/**
 * Reads the codepoints of the previous build from the committed SCSS map so
 * existing icons keep their glyph across builds; only new icons get new
 * codepoints.
 */
async function readPreviousCodepoints() {
    const scss = await fs.readFile(SCSS_OUT, "utf8").catch(() => "");
    const codepoints = {};
    for (const [, name, hex] of scss.matchAll(/^\s*"([^"]+)":\s*"\\([0-9a-fA-F]+)"/gm)) {
        codepoints[name] = parseInt(hex, 16);
    }
    return codepoints;
}

/**
 * Fantasticon 4.x builds each glyph's character with String.fromCharCode(),
 * which truncates codepoints above U+FFFF to 16 bits (U+1F90E -> U+F90E).
 * The font then has no glyph at the published codepoint and browsers fall
 * back to the colour emoji font. Map single astral arguments to
 * String.fromCodePoint() for the duration of the font build only.
 */
async function withAstralSafeFromCharCode(fn) {
    const fromCharCode = String.fromCharCode;
    String.fromCharCode = function (...codes) {
        return codes.length === 1 && codes[0] > 0xffff
            ? String.fromCodePoint(codes[0])
            : fromCharCode.apply(String, codes);
    };
    try {
        return await fn();
    } finally {
        String.fromCharCode = fromCharCode;
    }
}

/** Fails the build if any glyph landed on a codepoint other than its pinned one. */
function assertGlyphCodepoints(glyphs, codepoints) {
    const wrong = glyphs.filter(({ name, unicode }) => unicode?.[0]?.codePointAt(0) !== codepoints[name]);
    if (!glyphs.length || wrong.length) {
        throw new Error(
            `[build-font] ${glyphs.length ? wrong.length : "all"} glyphs not at their codepoint: ` +
                wrong
                    .slice(0, 10)
                    .map(({ name }) => name)
                    .join(", ")
        );
    }
}

function renderScss(codepoints) {
    const names = Object.keys(codepoints).sort();
    const lines = [];
    lines.push("// AUTO-GENERATED by scripts/build-font.mjs — do not edit by hand.");
    lines.push("// Source of truth: src/svg/**/*.svg + dist/font/icongl.json.");
    lines.push("");
    lines.push("// ============================================================================");
    lines.push("// Icon.gl | Font Variables");
    lines.push("// ============================================================================");
    lines.push("");
    lines.push(`$icon_name: "${FONT_NAME}" !default;`);
    lines.push(`$icon_dir: "../font" !default;`);
    lines.push("");
    lines.push("$icongl_font_formats: (");
    lines.push('    "woff2": "woff2",');
    lines.push('    "woff": "woff",');
    lines.push(");");
    lines.push("");
    lines.push("$icongl_map: (");
    for (const name of names) {
        const hex = codepoints[name].toString(16);
        lines.push(`    "${name}": "\\${hex}",`);
    }
    lines.push(");");
    lines.push("");
    return lines.join("\n");
}

async function main() {
    await fs.mkdir(OUTPUT_DIR, { recursive: true });

    const icons = (await collectIcons()).filter((icon) => !SKIP_FOLDERS.has(icon.folder));
    const ids = new Set(icons.map((icon) => icon.id));
    console.log(`[build-font] ${icons.length} svg sources discovered (no name collisions)`);

    const previous = await readPreviousCodepoints();
    const pinned = Object.fromEntries(Object.entries(previous).filter(([id]) => ids.has(id)));
    const reserved = new Set(Object.values(previous));
    // Number new icons above the whole previous map (removed icons included)
    // so a cached font never shows a just-removed glyph for a new icon.
    let next = Math.max(0xf101 - 1, ...reserved) + 1;
    const codepoints = { ...pinned };
    for (const { id } of icons) {
        if (codepoints[id] === undefined) codepoints[id] = next++;
    }
    const added = icons.length - Object.keys(pinned).length;
    console.log(`[build-font] ${Object.keys(pinned).length} codepoints pinned, ${added} new`);

    // Fantasticon takes a single flat folder, so stage the selected SVGs.
    await fs.rm(TEMP_DIR, { recursive: true, force: true });
    await fs.mkdir(TEMP_DIR, { recursive: true });
    try {
        for (const { id, file } of icons) {
            await fs.copyFile(file, path.join(TEMP_DIR, `${id}.svg`));
        }

        let glyphs = [];
        await withAstralSafeFromCharCode(() =>
            generateFonts({
                inputDir: TEMP_DIR,
                outputDir: OUTPUT_DIR,
                name: FONT_NAME,
                fontTypes: [FontAssetType.WOFF2, FontAssetType.WOFF],
                assetTypes: [OtherAssetType.JSON, OtherAssetType.TS],
                normalize: true,
                codepoints,
                getIconId: ({ basename }) => basename,
                // svgicons2svgfont reports the glyphs it wrote into the font.
                formatOptions: { svg: { callback: (written) => (glyphs = written) } },
            })
        );
        assertGlyphCodepoints(glyphs, codepoints);
    } finally {
        await fs.rm(TEMP_DIR, { recursive: true, force: true });
    }

    const jsonPath = path.join(OUTPUT_DIR, `${FONT_NAME}.json`);
    const fontCodepoints = JSON.parse(await fs.readFile(jsonPath, "utf8"));

    const missing = [...ids].filter((id) => !(id in fontCodepoints));
    if (missing.length) {
        throw new Error(
            `[build-font] ${missing.length} svgs missing from font: ` +
                missing.slice(0, 10).join(", ") +
                (missing.length > 10 ? ", ..." : "")
        );
    }
    console.log(`[build-font] ${ids.size} icons in font, all svgs covered`);

    // Skip unchanged writes so watchers on src/ don't retrigger the build.
    const scss = renderScss(fontCodepoints);
    if ((await fs.readFile(SCSS_OUT, "utf8").catch(() => null)) !== scss) {
        await fs.writeFile(SCSS_OUT, scss, "utf8");
        console.log(`[build-font] wrote ${path.relative(ROOT, SCSS_OUT)}`);
    }
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
